# Generated by Django 5.1.3 on 2024-11-25 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pelanggan', models.CharField(max_length=100)),
                ('alamat_pelanggan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Penjualan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_penjualan', models.DateField()),
                ('jumlah_terjual', models.PositiveIntegerField()),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_produk', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Tidak Tersedia', 'Tidak Tersedia')], max_length=50)),
                ('kategori', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('status_pembayaran', models.CharField(choices=[('LUNAS', 'Lunas'), ('BELUM_LUNAS', 'Belum Lunas'), ('MENUNGGU', 'Menunggu Pembayaran')], default='MENUNGGU', max_length=20)),
                ('metode', models.CharField(choices=[('TRANSFER', 'Transfer Bank'), ('TUNAI', 'Tunai'), ('KARTU', 'Kartu Kredit/Debit'), ('EWALLET', 'E-Wallet')], max_length=20)),
                ('idPelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayarans', to='umkmapp.pelanggan')),
                ('idPenjualan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pembayarans', to='umkmapp.penjualan')),
            ],
        ),
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal_pengiriman', models.DateField()),
                ('estimasi', models.CharField(max_length=50)),
                ('idPelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengirimans', to='umkmapp.pelanggan')),
            ],
        ),
        migrations.AddField(
            model_name='penjualan',
            name='idProduk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penjualans', to='umkmapp.produk'),
        ),
        migrations.AddField(
            model_name='pelanggan',
            name='idProduk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pelanggans', to='umkmapp.produk'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_supplier', models.CharField(max_length=100)),
                ('alamat_supplier', models.TextField()),
                ('idProduk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='umkmapp.produk')),
            ],
        ),
        migrations.AddField(
            model_name='produk',
            name='idUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produks', to='umkmapp.user'),
        ),
        migrations.CreateModel(
            name='Pendapatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(max_length=50)),
                ('total_pendapatan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendapatans', to='umkmapp.pembayaran')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendapatans', to='umkmapp.user')),
            ],
        ),
    ]
