# Generated by Django 5.1.3 on 2024-12-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkmapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], default='USER', max_length=20),
        ),
    ]
