# Generated by Django 5.1.3 on 2024-12-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkmapp', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='produk_images/', verbose_name='Gambar Produk'),
        ),
    ]
