# Generated by Django 5.1.3 on 2024-12-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umkmapp', '0003_produk_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='produk/', verbose_name='Gambar Produk'),
        ),
    ]
